# Generated by Django 5.1.4 on 2025-01-02 07:07

import Book.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('birthday', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('from_country', models.CharField(choices=[('IRAN', 'ایرانی'), ('FRANCH', 'فرانسوی'), ('RUSSIAN', 'روسی')], default='IRAN', max_length=30, verbose_name='از کشور')),
                ('about_author', models.TextField(verbose_name='زندگینامه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='اسلاگ')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=30, verbose_name='نام ژانر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='اسلاگ')),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category_name', models.CharField(max_length=20, verbose_name='نام دسته بندی اصلی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='اسلاگ')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=50)),
                ('about_publisher', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='اسلاگ')),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category_name', models.CharField(max_length=20, verbose_name='نام دسته ی فرزند')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='childToParentCategory', to='Book.parentcategory', verbose_name='دسته بندی والد')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_created=True, verbose_name='تاریخ ایجاد')),
                ('book_name', models.CharField(max_length=100, verbose_name='نام کتاب')),
                ('number_page', models.IntegerField(verbose_name='تعداد صفحات')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='اسلاگ')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('unit_price', models.PositiveIntegerField(validators=[Book.validators.validatedPrice], verbose_name='قیمت واحد')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس است')),
                ('part_of_book', models.TextField(blank=True, null=True, verbose_name='بخشی از کتاب')),
                ('about_book', models.TextField(blank=True, null=True, verbose_name='درباره کتاب')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_books', to='Book.author', verbose_name='نویسنده')),
                ('child_category', models.ManyToManyField(to='Book.childcategory')),
                ('genre', models.ManyToManyField(to='Book.genre')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_cat_book', to='Book.parentcategory', verbose_name='دسته بندی اصلی')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher_books', to='Book.publisher', verbose_name='ناشر')),
            ],
        ),
    ]
