# Generated by Django 5.1.4 on 2025-01-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_book_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='about_publisher',
            field=models.TextField(verbose_name='درباره نشر'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='manager',
            field=models.CharField(max_length=50, verbose_name='موسس'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name',
            field=models.CharField(max_length=100, verbose_name='نام انتشارات'),
        ),
    ]
