# Generated by Django 5.1.4 on 2025-01-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_childcategory_slug_alter_publisher_about_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/image'),
        ),
    ]
